import { Job, Resume } from '@/types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    company_name: '제주 하얏트 호텔 협력사',
    title: '특급 호텔 룸메이드 및 객실 정비 인력 정규/파트타임 모집',
    target_worker_type: 'all',
    category: '룸메이드',
    eligible_visas: ['F-2', 'F-4', 'F-5', 'F-6', 'H-2', 'D-2'],
    region_sido: '제주',
    region_detail: '제주시 노형동',
    salary_type: 'monthly',
    salary_amount: '월 2,750,000원 + 인센티브',
    work_hours: '09:00 ~ 18:00 (주 5일)',
    description: '초보자도 환영하며 체계적인 직무 교육을 제공합니다. 기숙사 및 중식 제공, 4대보험 완비.',
    contact_phone: '064-711-8578',
    status: 'active',
    views_count: 142,
    created_at: '2026-09-15'
  },
  {
    id: '2',
    company_name: '(주)동성 정밀제조',
    title: '자동차 부품 가공 및 CNC 머시닝 센터 오퍼레이터',
    target_worker_type: 'foreigner',
    category: '제조업',
    eligible_visas: ['E-7', 'E-9', 'F-4', 'H-2'],
    region_sido: '경기',
    region_detail: '화성시 향남',
    salary_type: 'monthly',
    salary_amount: '월 3,200,000원 ~ 3,600,000원',
    work_hours: '주간/야간 교대 (잔업수당 별도)',
    description: 'E-7 특정활동비자 보유자 및 F-4 외국국적동포 환영. 기숙사 1인 1실 제공.',
    contact_phone: '010-5731-8578',
    status: 'active',
    views_count: 89,
    created_at: '2026-09-14'
  },
  {
    id: '3',
    company_name: '오션뷰 리조트 & 스파',
    title: '리조트 단지 환경 미화 및 실내 클리닝 스태프',
    target_worker_type: 'all',
    category: '청소',
    eligible_visas: ['F-4', 'F-5', 'F-6', 'H-2', '내국인'],
    region_sido: '제주',
    region_detail: '서귀포시 중문',
    salary_type: 'monthly',
    salary_amount: '월 2,600,000원',
    work_hours: '08:30 ~ 17:30',
    description: '쾌적한 환경에서 근무하실 청소 인력을 모십니다. 셔틀버스 운행.',
    contact_phone: '064-711-8578',
    status: 'active',
    views_count: 67,
    created_at: '2026-09-13'
  },
  {
    id: '4',
    company_name: '글로벌 어학원',
    title: '초/중등 방과후 원어민 회화 및 영어 놀이 도우미',
    target_worker_type: 'foreigner',
    category: '영어도우미',
    eligible_visas: ['E-2', 'F-4', 'F-6', 'D-2(시간제)'],
    region_sido: '서울',
    region_detail: '강남구 역삼동',
    salary_type: 'hourly',
    salary_amount: '시급 35,000원',
    work_hours: '화/목 14:00 ~ 18:00',
    description: '어학연수 및 유학생 시간제 취업허가(D-2) 학생 지원 가능.',
    contact_phone: '010-5731-8578',
    status: 'active',
    views_count: 215,
    created_at: '2026-09-12'
  },
  {
    id: '5',
    company_name: '현대중공업 협력사',
    title: '조선소 선박 배관 용접 및 TIG 특수용접 기술자 급구',
    target_worker_type: 'all',
    category: '용접공',
    eligible_visas: ['E-7-1', 'E-7-3', 'F-4', '내국인'],
    region_sido: '울산',
    region_detail: '울산 동구',
    salary_type: 'monthly',
    salary_amount: '월 4,000,000원 ~ 4,800,000원',
    work_hours: '08:00 ~ 18:00',
    description: '조선업 E-7 비자 기술 인력 적극 환영. 비자 연장 및 체류 지원 행정 지원.',
    contact_phone: '064-711-8578',
    status: 'active',
    views_count: 310,
    created_at: '2026-09-10'
  }
];

export const MOCK_RESUMES: Resume[] = [
  {
    id: 'r1',
    title: 'F-4 비자 제조업 및 호텔 룸메이드 경력 3년 성실한 남성입니다',
    worker_type: 'foreigner',
    visa_type: 'F-4 (재외동포)',
    nationality: '중국 동포',
    gender: '남성',
    age: 36,
    desired_category: '룸메이드 / 청소',
    desired_region: '제주 / 전국',
    korean_level: '유창함 (한국어능력시험 고급)',
    introduction: '호텔 객실 청소 및 기숙사 생활 가능하며 장기 근무를 희망합니다.',
    contact_phone: '010-****-1234',
    status: 'active',
    created_at: '2026-09-16'
  },
  {
    id: 'r2',
    title: 'D-2 유학생 평일 저녁/주말 식음료 및 홀서빙 파트타임 구합니다',
    worker_type: 'foreigner',
    visa_type: 'D-2 (유학)',
    nationality: '베트남',
    gender: '여성',
    age: 23,
    desired_category: '유학생알바 / 홀서빙',
    desired_region: '제주 / 서울',
    korean_level: 'TOPIK 4급 (의사소통 원활)',
    introduction: '출입국 시간제 취업허가증 구비 완료. 성실하게 일하겠습니다.',
    contact_phone: '010-****-5678',
    status: 'active',
    created_at: '2026-09-15'
  },
  {
    id: 'r3',
    title: 'E-7 조선소 및 플랜트 TIG 용접 5년 경력자 일자리 구합니다',
    worker_type: 'foreigner',
    visa_type: 'E-7 (특정활동)',
    nationality: '우즈베키스탄',
    gender: '남성',
    age: 32,
    desired_category: '용접공',
    desired_region: '울산 / 거제 / 전국',
    korean_level: '중급 (업무 소통 가능)',
    introduction: '용접 자격증 보유, 비자 연장 가능한 건실한 기업을 찾습니다.',
    contact_phone: '010-****-9012',
    status: 'active',
    created_at: '2026-09-14'
  }
];
