'use client';

import React, { createContext, useContext, useState } from 'react';

export type Language = 'ko' | 'en' | 'zh' | 'vi' | 'th' | 'id' | 'uz';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'ko', name: '한국어', nativeName: '한국어', flag: 'https://flagcdn.com/w80/kr.png' },
  { code: 'en', name: '영어', nativeName: 'English', flag: 'https://flagcdn.com/w80/us.png' },
  { code: 'zh', name: '중국어', nativeName: '中文', flag: 'https://flagcdn.com/w80/cn.png' },
  { code: 'vi', name: '베트남어', nativeName: 'Tiếng Việt', flag: 'https://flagcdn.com/w80/vn.png' },
  { code: 'th', name: '태국어', nativeName: 'ไทย', flag: 'https://flagcdn.com/w80/th.png' },
  { code: 'id', name: '인도네시아어', nativeName: 'Bahasa Indonesia', flag: 'https://flagcdn.com/w80/id.png' },
  { code: 'uz', name: '우즈베크어', nativeName: 'Oʻzbek', flag: 'https://flagcdn.com/w80/uz.png' },
];

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Navigation
    home: '홈',
    about: '회사소개',
    jobs: '구인',
    resumes: '구직',
    studentJobs: '유학생 취업',
    partTime: '아르바이트',
    visaInquiry: '비자/행정상담',
    community: '커뮤니티',
    login: '로그인',
    postJob: '공고 등록',

    // Official Registration
    regLicense: '국외유료직업소개사업 등록기관 f1630120240001',
    regSub: 'Registered overseas job placement agency',

    // Core Hero Slide 1
    heroJejuBadge: 'JOB IN JEJU ISLAND & GLOBAL MANPOWER',
    heroBadge: '국외유료직업소개 등록기관 | 비자 발급·대행 전문',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: '외국인 인력공급 · 합법 비자대행',
    heroSubtitle: '외국인 인력공급 · 취업알선 · 비자발급 대행 · 한국유학&어학연수 · 전문 하우스키퍼까지 원스톱으로 지원합니다.',
    targetVisaLabel: '지원 대상 비자 자격:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · F계열 합법 취업',
    findJobBtn: '외국인 일자리 찾기',
    freeVisaBtn: '비자 발급 무료 상담',

    // Hero Slide 2
    slide2Badge: '기업 맞춤형 상시 인력 파견 · 도급 · 채용 대행',
    slide2Title1: '필요한 현장에 검증된 인재를,',
    slide2Title2: 'We supply Manpower',
    slide2Desc: '특급 호텔·리조트 룸메이드, 하우스키퍼, 조선소 선박 배관 용접사, 자동차 부품 및 식품 가공 제조업 숙련 인력을 신속하고 정확하게 공급합니다.',
    slide2Btn1: '전문 인력 공고 보러가기',
    slide2Btn2: '기업 인력 요청 상담 (064-711-8578)',
    slide2ImgBadge: '철저한 신원 보증 & 합법 비자 체류 확인',

    // Hero Slide 3
    slide3Badge: '글로벌 어학연수 · 유학 · 비자 행정 전문',
    slide3Title1: '한국 유학부터 합법 취업까지,',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: '외국인 유학생(D-2, D-4) 비자 발급, 어학연수 매칭 및 출입국관리사무소 시간제 취업 허가증 발급 행정 절차를 완벽 지원합니다.',
    slide3Card1Title: 'D-2 유학생 시간제 취업',
    slide3Card1Desc: '주중 식음료/서비스 및 주말 파트타임 알선',
    slide3Card2Title: 'E-7/F-4 체류자격 변경',
    slide3Card2Desc: '졸업 후 전문 취업비자 연계 및 체류 연장',
    slide3Btn: '유학·비자 무료 행정상담 신청',

    // Search bar
    searchPlaceholder: '찾으시는 회사명, 직종(룸메이드, 용접 등), 지역을 입력해주세요.',
    btnSearch: '검색하기',

    // 16 countries card
    networkTitle: '16개국 공식 송출 · 취업 네트워크',
    networkBadge: '16개 협력국',
    networkFooter: '합법 비자 취업 지원 협약국',
    verifiedTalent: '신원 보증',

    // Sidebars
    regionTitle: '지역별 구인 / 구직',
    regionBadge: '전국',
    jobTypeTitle: '직종별 구인 / 구직',
    jobTypeBadge: '원클릭 이동',
    quickOffer: '구인',
    quickSeek: '구직',
    urgentCallTitle: '인력 급구 & 비자 즉시 상담',
    urgentCallBtn: '전화 바로 걸기',

    // Lists
    jobOffersTitle: '구인정보',
    jobSeekersTitle: '구직정보',
    totalCount: '총 {count}건',
    totalPeople: '총 {count}명',
    viewMore: '더보기',
    thCategory: '분야',
    thTitle: '제목',
    thSalary: '급여',
    thRegion: '지역',
    thDate: '등록일',
    thType: '구분',
    thVisaInfo: '비자/연령',

    // 5 Core Pillars Section
    pillarsTitle: '록산에버그린 5대 핵심 전문 분야',
    pillarsSubtitle: '기존 인트로 핵심 정체성을 계승한 5대 외국인 종합 고용 및 비자 지원 서비스',
    pillar1Title: '외국인 인력공급',
    pillar1Sub: 'Foreign Labor Supply / 外国人力供应',
    pillar1Desc: '제조, 농축산, 어업, 관광/서비스 등 국내 산업군 맞춤 숙련 인력 상시 공급',
    pillar2Title: '취업알선',
    pillar2Sub: 'Job Placement / 就业中介',
    pillar2Desc: '외국인 전문 구직자 ↔ 제주 및 전국 고용 기업 간 1:1 정밀 매칭 및 사후관리',
    pillar3Title: '비자발급 · 대행',
    pillar3Sub: 'Visa Issuance Agency / 签证发放,代理',
    pillar3Desc: 'E-7, E-9, D-2, F-4 등 출입국 비자 행정 서류 발급, 자격변경 및 체류 연장 대행',
    pillar4Title: '한국유학&어학연수',
    pillar4Sub: 'Study Abroad / 韩国留学&语言研修',
    pillar4Desc: '외국인 유학생 유치 연계, 국내 대학 입학/연수 및 합법적 D-2 아르바이트 지원',
    pillar5Title: '하우스키퍼 (룸메이드)',
    pillar5Sub: 'Housekeeper / 管家',
    pillar5Desc: '제주 특급호텔, 리조트, 펜션 등 객실 정비 및 시설관리 특화 전문 인력 파견',

    // Footer
    companyName: '록산에버그린 주식회사',
    address: '제주특별자치도 제주시 서광로 107-6 (용담이동)',
    ceo: '대표자 : 김찬식',
    bizNum: '사업자등록번호 : 616-81-02802',
    phone: '전화 : 064-711-8578 / 010-5731-8578',
    email: '이메일 : roksan22@daum.net',
    affiliates: '유관기관 바로가기'
  },
  en: {
    // Navigation
    home: 'Home',
    about: 'About Us',
    jobs: 'Jobs',
    resumes: 'Talents',
    studentJobs: 'Student Jobs',
    partTime: 'Part-Time',
    visaInquiry: 'Visa / Consulting',
    community: 'Community',
    login: 'Login',
    postJob: 'Post Job',

    // Official Registration
    regLicense: 'Overseas Job Placement Agency Lic. f1630120240001',
    regSub: 'Registered overseas job placement agency',

    // Core Hero Slide 1
    heroJejuBadge: 'JOB IN JEJU ISLAND & GLOBAL MANPOWER',
    heroBadge: 'Registered Overseas Placement Agency | Visa Specialist',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: 'Foreign Labor Supply & Visa Agency',
    heroSubtitle: 'One-stop support for Foreign labor supply · Job placement · Visa issuance agency · Study in Korea & language training · Professional housekeepers.',
    targetVisaLabel: 'Supported Visa Types:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · F-Visas Legal Employment',
    findJobBtn: 'Find Jobs in Korea',
    freeVisaBtn: 'Free Visa Consultation',

    // Hero Slide 2
    slide2Badge: 'Custom Manpower Dispatch · Contracting · Recruitment Agency',
    slide2Title1: 'Verified Talents for Your Workplace,',
    slide2Title2: 'We supply Manpower',
    slide2Desc: 'Promptly providing skilled workers for luxury hotels, resorts, room-maids, housekeepers, shipyard TIG welders, automotive parts, and food manufacturing.',
    slide2Btn1: 'Browse Specialized Jobs',
    slide2Btn2: 'Manpower Request Call (+82-64-711-8578)',
    slide2ImgBadge: 'Strict Identity Verification & Legal Visa Residency',

    // Hero Slide 3
    slide3Badge: 'Global Language Training · Study Abroad · Visa Administration',
    slide3Title1: 'From Studying in Korea to Employment,',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: 'Comprehensive support for international student (D-2, D-4) visas, language training matching, and immigration part-time work permit procedures.',
    slide3Card1Title: 'D-2 Student Part-Time Jobs',
    slide3Card1Desc: 'Weekday F&B, service jobs, and weekend part-time placements',
    slide3Card2Title: 'E-7 / F-4 Visa Status Change',
    slide3Card2Desc: 'Post-graduation professional work visa linkage and residency extensions',
    slide3Btn: 'Apply for Free Study & Visa Consultation',

    // Search bar
    searchPlaceholder: 'Search company, job category (Room-maid, Welder, etc.), region...',
    btnSearch: 'Search',

    // 16 countries card
    networkTitle: '16 Sending Countries Network',
    networkBadge: '16 Countries',
    networkFooter: 'Legal Employment Partner Countries',
    verifiedTalent: 'Identity Verified',

    // Sidebars
    regionTitle: 'Jobs by Region',
    regionBadge: 'Nationwide',
    jobTypeTitle: 'Jobs by Category',
    jobTypeBadge: 'Quick Jump',
    quickOffer: 'Hiring',
    quickSeek: 'Seeking',
    urgentCallTitle: 'Urgent Manpower & Visa Hotline',
    urgentCallBtn: 'Call Immediately',

    // Lists
    jobOffersTitle: 'Job Offers',
    jobSeekersTitle: 'Talent Profiles',
    totalCount: 'Total {count}',
    totalPeople: 'Total {count} talents',
    viewMore: 'More',
    thCategory: 'Category',
    thTitle: 'Title',
    thSalary: 'Salary',
    thRegion: 'Region',
    thDate: 'Date',
    thType: 'Type',
    thVisaInfo: 'Visa/Age',

    // 5 Core Pillars Section
    pillarsTitle: 'Our 5 Core Business Pillars',
    pillarsSubtitle: 'Dedicated global manpower and legal visa services continuing our foundational identity',
    pillar1Title: 'Foreign Labor Supply',
    pillar1Sub: 'Foreign Labor Supply / 外国人力供应',
    pillar1Desc: 'Supplying skilled global manpower for manufacturing, agriculture, fisheries, tourism, and services',
    pillar2Title: 'Job Placement',
    pillar2Sub: 'Job Placement / 就业中介',
    pillar2Desc: '1:1 precise matching and continuous care between foreign talents and enterprises in Jeju & nationwide',
    pillar3Title: 'Visa Issuance & Agency',
    pillar3Sub: 'Visa Issuance Agency / 签证发放,代理',
    pillar3Desc: 'Immigration administrative documentation, status change, and extension agency for E-7, E-9, D-2, F-4, etc.',
    pillar4Title: 'Study Abroad & Language',
    pillar4Sub: 'Study Abroad / 韩国留学&语言研修',
    pillar4Desc: 'Recruitment and admissions to Korean universities, language institutes, and legal D-2 student part-time support',
    pillar5Title: 'Housekeeper (Room-maid)',
    pillar5Sub: 'Housekeeper / 管家',
    pillar5Desc: 'Specialized staffing for luxury hotels, resorts, and villas in Jeju for room maintenance and facility care',

    // Footer
    companyName: 'Roksan Evergreen Co., Ltd.',
    address: '107-6, Seogwang-ro, Jeju-si, Jeju-do, Republic of Korea',
    ceo: 'CEO: Chan-sik Kim',
    bizNum: 'Business Reg. No: 616-81-02802',
    phone: 'Tel : +82-64-711-8578 / +82-10-5731-8578',
    email: 'Email : roksan22@daum.net',
    affiliates: 'Related Organizations'
  },
  zh: {
    // Navigation
    home: '首页',
    about: '公司介绍',
    jobs: '招聘信息',
    resumes: '求职人才',
    studentJobs: '留学生就业',
    partTime: '兼职打工',
    visaInquiry: '签证/行政咨询',
    community: '互动社区',
    login: '登录',
    postJob: '发布招聘',

    // Official Registration
    regLicense: '国外有偿职业介绍登记许可机构 f1630120240001',
    regSub: 'Registered overseas job placement agency',

    // Core Hero Slide 1
    heroJejuBadge: 'JOB IN JEJU ISLAND & 国际人力专业机构',
    heroBadge: '国外职业介绍许可机关 | 签证发放·代理专业机构',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: '外国人人力供应 · 合法签证代理',
    heroSubtitle: '外国人人力供应 · 就业中介 · 签证发放与代理 · 韩国留学&语言研修 · 专业管家(Housekeeper)一站式服务。',
    targetVisaLabel: '支持在留签证资格:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · F系列 合法就业',
    findJobBtn: '寻找韩国工作',
    freeVisaBtn: '免费签证咨询',

    // Hero Slide 2
    slide2Badge: '企业定制常驻派遣 · 外包 · 招聘代理',
    slide2Title1: '为所需现场输送经核实的优秀人才,',
    slide2Title2: 'We supply Manpower',
    slide2Desc: '快速精准供应特级酒店·度假村客房清扫(管家)、造船厂TIG管道焊工、汽车配件及食品加工制造熟练工。',
    slide2Btn1: '查看专业人才职位',
    slide2Btn2: '企业用工咨询 (+82-64-711-8578)',
    slide2ImgBadge: '严格身份核实 & 合法在留资格确认',

    // Hero Slide 3
    slide3Badge: '全球语言研修 · 韩国留学 · 签证行政专业机构',
    slide3Title1: '从韩国留学到合法就业,',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: '全方位支持外国留学生(D-2, D-4)签证签发、语言研修对接及出入境打工许可证申请等行政手续。',
    slide3Card1Title: 'D-2 留学生勤工俭学',
    slide3Card1Desc: '周中餐饮/服务及周末兼职精准推荐',
    slide3Card2Title: 'E-7 / F-4 在留资格变更',
    slide3Card2Desc: '毕业后专业工作签证对接与居留延期',
    slide3Btn: '申请免费留学·签证行政咨询',

    // Search bar
    searchPlaceholder: '请输入公司名称、职位(客房清扫、焊接工等)或地区...',
    btnSearch: '立即搜索',

    // 16 countries card
    networkTitle: '16个输送国官方就业网络',
    networkBadge: '16个合作国',
    networkFooter: '合法签证就业协议国',
    verifiedTalent: '身份保障',

    // Sidebars
    regionTitle: '按地区 招聘 / 求职',
    regionBadge: '全韩',
    jobTypeTitle: '按职位 招聘 / 求职',
    jobTypeBadge: '快速直达',
    quickOffer: '招聘',
    quickSeek: '求职',
    urgentCallTitle: '用工急聘 & 签证快速热线',
    urgentCallBtn: '立即拨打电话',

    // Lists
    jobOffersTitle: '招聘信息',
    jobSeekersTitle: '求职人才',
    totalCount: '共 {count} 条',
    totalPeople: '共 {count} 名',
    viewMore: '查看更多',
    thCategory: '类别',
    thTitle: '标题',
    thSalary: '薪资',
    thRegion: '地区',
    thDate: '日期',
    thType: '类型',
    thVisaInfo: '签证/年龄',

    // 5 Core Pillars Section
    pillarsTitle: '禄山常青 5大核心专业领域',
    pillarsSubtitle: '传承核心经营理念的5大外国人综合就业与签证代理服务',
    pillar1Title: '外国人人力供应',
    pillar1Sub: 'Foreign Labor Supply / 外国人力供应',
    pillar1Desc: '常年供应制造业、农畜业、渔业、观光及餐饮服务等领域熟练技术工人',
    pillar2Title: '就业中介',
    pillar2Sub: 'Job Placement / 就业中介',
    pillar2Desc: '外国专业人才与济州及韩国各地招聘企业间1:1精准对接与全程跟踪服务',
    pillar3Title: '签证签发 · 代理',
    pillar3Sub: 'Visa Issuance Agency / 签证发放,代理',
    pillar3Desc: '全权代理E-7, E-9, D-2, F-4等出入境行政文件签发、在留资格变更及签证延期',
    pillar4Title: '韩国留学&语言研修',
    pillar4Sub: 'Study Abroad / 韩国留学&语言研修',
    pillar4Desc: '留学生招募对接、韩国知名大学入学/语学堂研修及合法D-2兼职许可支持',
    pillar5Title: '专业管家 (客房清扫)',
    pillar5Sub: 'Housekeeper / 管家',
    pillar5Desc: '面向济州特级酒店、高端度假村及独栋别墅输送客房整备与设施管理专业人才',

    // Footer
    companyName: '禄山常青 股份有限公司 (Roksan Evergreen Co., Ltd.)',
    address: '韩国济州特别自治道济州市西光路 107-6 (龙潭二洞)',
    ceo: '代表 : 金赞植',
    bizNum: '企业注册号 : 616-81-02802',
    phone: '电话 : +82-64-711-8578 / +82-10-5731-8578',
    email: '邮箱 : roksan22@daum.net',
    affiliates: '相关机构通道'
  },
  vi: {
    home: 'Trang chủ',
    about: 'Giới thiệu công ty',
    jobs: 'Tuyển dụng',
    resumes: 'Tìm việc',
    studentJobs: 'Việc làm du học sinh',
    partTime: 'Việc làm thêm',
    visaInquiry: 'Tư vấn Visa & Hành chính',
    community: 'Cộng đồng',
    login: 'Đăng nhập',
    postJob: 'Đăng tin tuyển dụng',
    regLicense: 'Cơ quan giới thiệu việc làm nước ngoài có giấy phép f1630120240001',
    regSub: 'Registered overseas job placement agency',
    heroJejuBadge: 'VIỆC LÀM TẠI ĐẢO JEJU & NHÂN LỰC TOÀN CẦU',
    heroBadge: 'Cơ quan giới thiệu việc làm hợp pháp | Chuyên gia Visa',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: 'Cung ứng nhân lực nước ngoài · Đại lý Visa',
    heroSubtitle: 'Dịch vụ trọn gói cung ứng nhân lực nước ngoài · Giới thiệu việc làm · Đại diện cấp visa · Du học & Đào tạo tiếng Hàn · Dọn dẹp phòng khách sạn chuyên nghiệp.',
    targetVisaLabel: 'Các loại Visa hỗ trợ:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · F-Visas Việc làm hợp pháp',
    findJobBtn: 'Tìm việc làm tại Hàn Quốc',
    freeVisaBtn: 'Tư vấn Visa miễn phí',
    slide2Badge: 'Phái cử nhân lực · Gia công · Đại lý tuyển dụng theo yêu cầu',
    slide2Title1: 'Cung cấp nhân tài đã qua kiểm định,',
    slide2Title2: 'We supply Manpower',
    slide2Desc: 'Cung cấp nhanh chóng nhân lực lành nghề cho khách sạn, khu nghỉ dưỡng, buồng phòng, thợ hàn ống TIG đóng tàu, linh kiện ô tô và chế biến thực phẩm.',
    slide2Btn1: 'Xem tin tuyển dụng',
    slide2Btn2: 'Yêu cầu nhân lực (+82-64-711-8578)',
    slide2ImgBadge: 'Xác minh danh tính & Visa cư trú hợp pháp',
    slide3Badge: 'Du học Hàn Quốc · Đào tạo ngôn ngữ · Hành chính Visa',
    slide3Title1: 'Từ du học Hàn Quốc đến việc làm hợp pháp,',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: 'Hỗ trợ toàn diện thủ tục xin visa du học sinh (D-2, D-4), kết nối trường học và giấy phép làm thêm bán thời gian từ Cục xuất nhập cảnh.',
    slide3Card1Title: 'D-2 Du học sinh làm thêm',
    slide3Card1Desc: 'Nhà hàng, khách sạn ngày trong tuần và làm thêm cuối tuần',
    slide3Card2Title: 'E-7 / F-4 Chuyển đổi Visa',
    slide3Card2Desc: 'Chuyển đổi visa chuyên môn và gia hạn cư trú sau tốt nghiệp',
    slide3Btn: 'Đăng ký tư vấn du học & visa miễn phí',
    searchPlaceholder: 'Tìm kiếm công ty, ngành nghề (buồng phòng, thợ hàn...), khu vực...',
    btnSearch: 'Tìm kiếm',
    networkTitle: 'Mạng lưới 16 quốc gia hợp tác tuyển dụng',
    networkBadge: '16 Quốc gia',
    networkFooter: 'Các quốc gia đối tác việc làm hợp pháp',
    verifiedTalent: 'Bảo đảm nhân thân',
    regionTitle: 'Việc làm theo khu vực',
    regionBadge: 'Toàn quốc',
    jobTypeTitle: 'Việc làm theo ngành nghề',
    jobTypeBadge: 'Xem nhanh',
    quickOffer: 'Tuyển dụng',
    quickSeek: 'Tìm việc',
    urgentCallTitle: 'Đường dây nóng tuyển dụng & Visa khẩn cấp',
    urgentCallBtn: 'Gọi điện ngay',
    jobOffersTitle: 'Thông tin tuyển dụng',
    jobSeekersTitle: 'Hồ sơ tìm việc',
    totalCount: 'Tổng {count} tin',
    totalPeople: 'Tổng {count} người',
    viewMore: 'Xem thêm',
    thCategory: 'Ngành nghề',
    thTitle: 'Tiêu đề',
    thSalary: 'Mức lương',
    thRegion: 'Khu vực',
    thDate: 'Ngày đăng',
    thType: 'Phân loại',
    thVisaInfo: 'Visa / Tuổi',
    pillarsTitle: '5 Lĩnh vực cốt lõi của Roksan Evergreen',
    pillarsSubtitle: 'Dịch vụ việc làm tổng hợp và hỗ trợ visa hợp pháp cho người nước ngoài',
    pillar1Title: 'Cung ứng nhân lực nước ngoài',
    pillar1Sub: 'Foreign Labor Supply / Cung ứng lao động',
    pillar1Desc: 'Cung cấp nhân lực cho ngành sản xuất chế tạo, nông nghiệp, thủy sản và dịch vụ',
    pillar2Title: 'Môi giới việc làm',
    pillar2Sub: 'Job Placement / Giới thiệu việc làm',
    pillar2Desc: 'Kết nối 1:1 chính xác giữa nhân lực nước ngoài và doanh nghiệp tại Jeju & toàn quốc',
    pillar3Title: 'Cấp & Đại diện Visa',
    pillar3Sub: 'Visa Issuance Agency / Đại lý Visa',
    pillar3Desc: 'Đại diện xử lý hồ sơ hành chính xuất nhập cảnh E-7, E-9, D-2, F-4, gia hạn và chuyển đổi visa',
    pillar4Title: 'Du học & Đào tạo tiếng Hàn',
    pillar4Sub: 'Study Abroad / Du học Hàn Quốc',
    pillar4Desc: 'Hỗ trợ nhập học trường đại học, học tiếng Hàn và giấy phép làm thêm hợp pháp D-2',
    pillar5Title: 'Dọn phòng khách sạn chuyên nghiệp',
    pillar5Sub: 'Housekeeper / Buồng phòng khách sạn',
    pillar5Desc: 'Cung cấp nhân viên buồng phòng chuyên nghiệp cho các khách sạn, resort cao cấp tại Jeju',
    companyName: 'Công ty Cổ phần Roksan Evergreen',
    address: '107-6, Seogwang-ro, Jeju-si, Jeju-do, Hàn Quốc',
    ceo: 'Đại diện : Kim Chan-sik',
    bizNum: 'Mã số doanh nghiệp : 616-81-02802',
    phone: 'Điện thoại : +82-64-711-8578 / +82-10-5731-8578',
    email: 'Email : roksan22@daum.net',
    affiliates: 'Cơ quan liên quan'
  },
  th: {
    home: 'หน้าแรก',
    about: 'เกี่ยวกับบริษัท',
    jobs: 'รับสมัครงาน',
    resumes: 'หางาน',
    studentJobs: 'งานนักศึกษา',
    partTime: 'พาร์ทไทม์',
    visaInquiry: 'ปรึกษาวีซ่า',
    community: 'ชุมชน',
    login: 'เข้าสู่ระบบ',
    postJob: 'ลงประกาศงาน',
    regLicense: 'หน่วยงานจัดหางานต่างประเทศ f1630120240001',
    regSub: 'Registered overseas job placement agency',
    heroJejuBadge: 'งานในเกาะเชจู & กำลังคนระดับโลก',
    heroBadge: 'จัดหางานต่างประเทศถูกกฎหมาย | ผู้เชี่ยวชาญวีซ่า',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: 'จัดส่งแรงงานต่างชาติ · ตัวแทนวีซ่า',
    heroSubtitle: 'จัดหาแรงงานต่างชาติ · แนะนำงาน · ตัวแทนยื่นวีซ่า · ศึกษาต่อเกาหลี · แม่บ้านโรงแรมมืออาชีพ',
    targetVisaLabel: 'วีซ่าที่รองรับ:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · กลุ่มวีซ่า F ทำงานถูกกฎหมาย',
    findJobBtn: 'ค้นหางานในเกาหลี',
    freeVisaBtn: 'ปรึกษาวีซ่าฟรี',
    slide2Badge: 'จัดส่งแรงงานตามสั่ง · เอาท์ซอร์ส · สรรหาบุคลากร',
    slide2Title1: 'จัดส่งบุคลากรที่ผ่านการตรวจสอบ',
    slide2Title2: 'We supply Manpower',
    slide2Desc: 'จัดส่งแรงงานฝีมือสำหรับโรงแรมหรู, รีสอร์ท, รูมเมด, ช่างเชื่อม TIG, ชิ้นส่วนรถยนต์ และผลิตอาหาร',
    slide2Btn1: 'ดูตำแหน่งงาน',
    slide2Btn2: 'ติดต่อขอกำลังคน (+82-64-711-8578)',
    slide2ImgBadge: 'ตรวจสอบประวัติเข้มงวด & พำนักถูกกฎหมาย',
    slide3Badge: 'เรียนภาษา · ศึกษาต่อ · เอกสารวีซ่า',
    slide3Title1: 'เรียนต่อถึงทำงานถูกกฎหมายในเกาหลี',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: 'สนับสนุนวีซ่านักศึกษา (D-2, D-4), สถาบันภาษา และใบอนุญาตทำงานพาร์ทไทม์',
    slide3Card1Title: 'D-2 ทำงานพาร์ทไทม์',
    slide3Card1Desc: 'งานร้านอาหาร/บริการวันธรรมดา และวันหยุด',
    slide3Card2Title: 'E-7 / F-4 เปลี่ยนวีซ่า',
    slide3Card2Desc: 'ต่อยอดวีซ่าทำงานวิชาชีพและต่ออายุพำนัก',
    slide3Btn: 'ปรึกษาเรียนและวีซ่าฟรี',
    searchPlaceholder: 'ค้นหาบริษัท, อาชีพ (รูมเมด, ช่างเชื่อม...), พื้นที่...',
    btnSearch: 'ค้นหา',
    networkTitle: 'เครือข่าย 16 ประเทศพันธมิตร',
    networkBadge: '16 ประเทศ',
    networkFooter: 'ประเทศความร่วมมือจ้างงานถูกกฎหมาย',
    verifiedTalent: 'รับรองประวัติ',
    regionTitle: 'งานตามภูมิภาค',
    regionBadge: 'ทั่วประเทศ',
    jobTypeTitle: 'งานตามสายอาชีพ',
    jobTypeBadge: 'ดูด่วน',
    quickOffer: 'รับสมัคร',
    quickSeek: 'หางาน',
    urgentCallTitle: 'สายด่วนกำลังคนและวีซ่า',
    urgentCallBtn: 'โทรทันที',
    jobOffersTitle: 'ข้อมูลรับสมัครงาน',
    jobSeekersTitle: 'ข้อมูลผู้หางาน',
    totalCount: 'ทั้งหมด {count} รายการ',
    totalPeople: 'ทั้งหมด {count} คน',
    viewMore: 'ดูเพิ่มเติม',
    thCategory: 'ประเภท',
    thTitle: 'หัวข้อ',
    thSalary: 'เงินเดือน',
    thRegion: 'พื้นที่',
    thDate: 'วันที่',
    thType: 'หมวด',
    thVisaInfo: 'วีซ่า/อายุ',
    pillarsTitle: '5 เสาหลักธุรกิจของ รกซานเอเวอร์กรีน',
    pillarsSubtitle: 'บริการจัดหางานและวีซ่าครบวงจรสำหรับชาวต่างชาติ',
    pillar1Title: 'จัดหาแรงงานต่างชาติ',
    pillar1Sub: 'Foreign Labor Supply / จัดส่งแรงงาน',
    pillar1Desc: 'จัดหาแรงงานสำหรับโรงงาน เกษตร ประมง และบริการ',
    pillar2Title: 'จัดหางาน',
    pillar2Sub: 'Job Placement / แนะนำงาน',
    pillar2Desc: 'จับคู่ 1:1 แรงงานต่างชาติกับบริษัทในเชจูและทั่วเกาหลี',
    pillar3Title: 'ออกวีซ่าและดำเนินเรื่อง',
    pillar3Sub: 'Visa Issuance Agency / ตัวแทนวีซ่า',
    pillar3Desc: 'ดำเนินเอกสาร E-7, E-9, D-2, F-4 เปลี่ยนและต่ออายุวีซ่า',
    pillar4Title: 'เรียนต่อและฝึกภาษาเกาหลี',
    pillar4Sub: 'Study Abroad / เรียนต่อเกาหลี',
    pillar4Desc: 'เข้ามหาวิทยาลัยเกาหลี สถาบันภาษา และขออนุญาตทำงาน D-2',
    pillar5Title: 'รูมเมดโรงแรมมืออาชีพ (Room-maid)',
    pillar5Sub: 'Housekeeper / รูมเมดโรงแรม',
    pillar5Desc: 'จัดส่งพนักงานดูแลห้องพักสำหรับโรงแรมและรีสอร์ทเชจู',
    companyName: 'บริษัท รกซานเอเวอร์กรีน จำกัด',
    address: '107-6, Seogwang-ro, Jeju-si, Jeju-do, เกาหลีใต้',
    ceo: 'กรรมการผู้จัดการ : คิม ชาน-ชิก',
    bizNum: 'เลขทะเบียนธุรกิจ : 616-81-02802',
    phone: 'โทร : +82-64-711-8578 / +82-10-5731-8578',
    email: 'อีเมล : roksan22@daum.net',
    affiliates: 'องค์กรที่เกี่ยวข้อง'
  },
  id: {
    home: 'Beranda',
    about: 'Tentang Kami',
    jobs: 'Lowongan Kerja',
    resumes: 'Pencari Kerja',
    studentJobs: 'Pekerjaan Mahasiswa',
    partTime: 'Paruh Waktu',
    visaInquiry: 'Konsultasi Visa & Legal',
    community: 'Komunitas',
    login: 'Masuk',
    postJob: 'Pasang Lowongan',
    regLicense: 'Lembaga Penempatan Kerja Luar Negeri Resmi f1630120240001',
    regSub: 'Registered overseas job placement agency',
    heroJejuBadge: 'PEKERJAAN DI PULAU JEJU & TENAGA KERJA GLOBAL',
    heroBadge: 'Lembaga Penempatan Resmi | Spesialis Visa Korea',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: 'Penyalur Tenaga Kerja Asing & Agen Visa Legal',
    heroSubtitle: 'Dukungan lengkap untuk penyaluran tenaga kerja asing · Penempatan kerja · Pengurusan visa · Studi di Korea & pelatihan bahasa · Housekeeper profesional.',
    targetVisaLabel: 'Jenis Visa yang Didukung:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · Visa F Kerja Legal',
    findJobBtn: 'Cari Kerja di Korea',
    freeVisaBtn: 'Konsultasi Visa Gratis',
    slide2Badge: 'Pengiriman Tenaga Kerja Kustom · Alih Daya · Agen Perekrutan',
    slide2Title1: 'Menyediakan Talenta Terverifikasi untuk Anda,',
    slide2Title2: 'We supply Manpower',
    slide2Desc: 'Menyediakan tenaga kerja terampil untuk hotel mewah, resor, room-maid, tukang las TIG galangan kapal, suku cadang otomotif, dan manufaktur makanan.',
    slide2Btn1: 'Lihat Lowongan Kerja',
    slide2Btn2: 'Permintaan Tenaga Kerja (+82-64-711-8578)',
    slide2ImgBadge: 'Verifikasi Identitas Ketat & Visa Izin Tinggal Legal',
    slide3Badge: 'Pelatihan Bahasa · Studi di Korea · Administrasi Visa',
    slide3Title1: 'Dari Kuliah di Korea hingga Bekerja Legal,',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: 'Bantuan menyeluruh untuk visa pelajar (D-2, D-4), pelatihan bahasa, dan pengurusan izin kerja paruh waktu imigrasi.',
    slide3Card1Title: 'D-2 Kerja Paruh Waktu Mahasiswa',
    slide3Card1Desc: 'Pekerjaan F&B/layanan hari kerja dan kerja paruh waktu akhir pekan',
    slide3Card2Title: 'E-7 / F-4 Perubahan Status Visa',
    slide3Card2Desc: 'Penyambungan visa kerja profesional pasca lulus dan perpanjangan izin tinggal',
    slide3Btn: 'Daftar Konsultasi Studi & Visa Gratis',
    searchPlaceholder: 'Cari nama perusahaan, kategori pekerjaan (room-maid, las...), wilayah...',
    btnSearch: 'Cari',
    networkTitle: 'Jaringan 16 Negara Pengirim Resmi',
    networkBadge: '16 Negara',
    networkFooter: 'Negara Mitra Kerja Legal',
    verifiedTalent: 'Identitas Terjamin',
    regionTitle: 'Pekerjaan Berdasarkan Wilayah',
    regionBadge: 'Seluruh Korea',
    jobTypeTitle: 'Pekerjaan Berdasarkan Kategori',
    jobTypeBadge: 'Akses Cepat',
    quickOffer: 'Lowongan',
    quickSeek: 'Pencari Kerja',
    urgentCallTitle: 'Hotline Darurat Tenaga Kerja & Visa',
    urgentCallBtn: 'Hubungi Sekarang',
    jobOffersTitle: 'Informasi Lowongan Kerja',
    jobSeekersTitle: 'Profil Pencari Kerja',
    totalCount: 'Total {count} lowongan',
    totalPeople: 'Total {count} orang',
    viewMore: 'Lihat Selengkapnya',
    thCategory: 'Kategori',
    thTitle: 'Judul',
    thSalary: 'Gaji',
    thRegion: 'Wilayah',
    thDate: 'Tanggal',
    thType: 'Tipe',
    thVisaInfo: 'Visa/Usia',
    pillarsTitle: '5 Pilar Bisnis Utama Roksan Evergreen',
    pillarsSubtitle: 'Layanan ketenagakerjaan komprehensif dan visa legal untuk warga negara asing',
    pillar1Title: 'Penyaluran Tenaga Kerja Asing',
    pillar1Sub: 'Foreign Labor Supply / Penyalur Tenaga Kerja',
    pillar1Desc: 'Menyediakan tenaga kerja terampil untuk manufaktur, pertanian, perikanan, dan perhotelan',
    pillar2Title: 'Penempatan Kerja',
    pillar2Sub: 'Job Placement / Penempatan Kerja',
    pillar2Desc: 'Pencocokan presisi 1:1 antara tenaga kerja asing dan perusahaan di Jeju & seluruh Korea',
    pillar3Title: 'Penerbitan & Agen Visa',
    pillar3Sub: 'Visa Issuance Agency / Pengurusan Visa',
    pillar3Desc: 'Pengurusan dokumen imigrasi untuk E-7, E-9, D-2, F-4, perubahan dan perpanjangan visa',
    pillar4Title: 'Studi di Korea & Bahasa',
    pillar4Sub: 'Study Abroad / Kuliah di Korea',
    pillar4Desc: 'Pendaftaran universitas Korea, kursus bahasa, dan izin kerja paruh waktu D-2',
    pillar5Title: 'Housekeeper Profesional (Room-maid)',
    pillar5Sub: 'Housekeeper / Tata Graha',
    pillar5Desc: 'Penyediaan staf room-maid untuk hotel dan resor mewah di Pulau Jeju',
    companyName: 'Roksan Evergreen Co., Ltd.',
    address: '107-6, Seogwang-ro, Jeju-si, Jeju-do, Republik Korea',
    ceo: 'CEO : Chan-sik Kim',
    bizNum: 'No. Pendaftaran Bisnis : 616-81-02802',
    phone: 'Telepon : +82-64-711-8578 / +82-10-5731-8578',
    email: 'Email : roksan22@daum.net',
    affiliates: 'Instansi Terkait'
  },
  uz: {
    home: 'Bosh sahifa',
    about: 'Kompaniya haqida',
    jobs: 'Ish o‘rinlari',
    resumes: 'Rezyumelar',
    studentJobs: 'Talabalar ishi',
    partTime: 'Yarim stavka',
    visaInquiry: 'Viza maslahati',
    community: 'Hamjamiyat',
    login: 'Kirish',
    postJob: 'E’lon berish',
    regLicense: 'Xorijiy ishga joylashtirish rasmiy agentligi f1630120240001',
    regSub: 'Registered overseas job placement agency',
    heroJejuBadge: 'JEJU OROLIDA ISH & XALQARO KADRLAR',
    heroBadge: 'Qonuniy xorijiy ish agentligi | Viza mutaxassisi',
    heroTitle1: 'JOB IN JEJU ISLAND',
    heroTitle2: 'Xorijiy ishchi kuchi · Qonuniy viza agentligi',
    heroSubtitle: 'Xorijiy ishchilar ta’minoti · Ishga joylashtirish · Viza rasmiylashtirish · Koreyada o‘qish · Professional mehmonxona xodimlari.',
    targetVisaLabel: 'Qo‘llab-quvvatlanadigan vizalar:',
    targetVisaList: 'E-7 · E-9 · D-2 · H-2 · F vizalari qonuniy ish',
    findJobBtn: 'Koreyada ish qidirish',
    freeVisaBtn: 'Bepul viza maslahati',
    slide2Badge: 'Maxsus kadrlar yuborish · Autsorsing · Yollash agentligi',
    slide2Title1: 'Tekshirilgan mutaxassislar ta’minoti',
    slide2Title2: 'We supply Manpower',
    slide2Desc: 'Mehmonxonalar, dam olish maskanlari, TIG payvandchilari, avto ehtiyot qismlar va ishlab chiqarishga malakali ishchilar.',
    slide2Btn1: 'Ishlarni ko‘rish',
    slide2Btn2: 'Kadrlar so‘rovi (+82-64-711-8578)',
    slide2ImgBadge: 'Qat’iy tekshiruv & Qonuniy viza',
    slide3Badge: 'Til o‘rganish · O‘qish · Viza ma’muriyati',
    slide3Title1: 'O‘qishdan qonuniy ishga joylashishgacha',
    slide3Title2: 'Language Training Arrangement',
    slide3Desc: 'Talaba vizalari (D-2, D-4), til kurslari va yarim stavka ishlash ruxsatnomalarini rasmiylashtirish.',
    slide3Card1Title: 'D-2 Talabalik ishlari',
    slide3Card1Desc: 'Restoran/xizmat va dam olish kunlari ishlari',
    slide3Card2Title: 'E-7 / F-4 Viza o‘zgartirish',
    slide3Card2Desc: 'Bitirgach professional ishchi vizasi va muddat uzaytirish',
    slide3Btn: 'Bepul maslahatga yozilish',
    searchPlaceholder: 'Kompaniya, kasb (tozalik xodimi, payvandchi...), hudud...',
    btnSearch: 'Qidirish',
    networkTitle: '16 ta hamkor davlat tarmog‘i',
    networkBadge: '16 Davlat',
    networkFooter: 'Qonuniy ish hamkor davlatlari',
    verifiedTalent: 'Kafolatlangan shaxs',
    regionTitle: 'Hududlar bo‘yicha',
    regionBadge: 'Butun Koreya',
    jobTypeTitle: 'Kasblar bo‘yicha',
    jobTypeBadge: 'Tezkor o‘tish',
    quickOffer: 'Ish beruvchi',
    quickSeek: 'Ish izlovchi',
    urgentCallTitle: 'Tezkor aloqa',
    urgentCallBtn: 'Qo‘ng‘iroq qiling',
    jobOffersTitle: 'Ish e’lonlari',
    jobSeekersTitle: 'Ish izlovchilar',
    totalCount: 'Jami {count} ta',
    totalPeople: 'Jami {count} kishi',
    viewMore: 'Ko‘rish',
    thCategory: 'Soha',
    thTitle: 'Sarlavha',
    thSalary: 'Maosh',
    thRegion: 'Hudud',
    thDate: 'Sana',
    thType: 'Turkum',
    thVisaInfo: 'Viza/Yosh',
    pillarsTitle: '5 Asosiy faoliyat yo‘nalishi',
    pillarsSubtitle: 'Xorijiy fuqarolar uchun bandlik va qonuniy viza xizmatlari',
    pillar1Title: 'Xorijiy ishchi kuchi ta’minoti',
    pillar1Sub: 'Foreign Labor Supply / Ishchi kuchi',
    pillar1Desc: 'Ishlab chiqarish, qishloq xo‘jaligi, baliqchilik va xizmat sohalari',
    pillar2Title: 'Ishga joylashtirish',
    pillar2Sub: 'Job Placement / Ishga joylash',
    pillar2Desc: 'Xorijiy ishchilar va korxonalar o‘rtasida 1:1 muvofiqlashtirish',
    pillar3Title: 'Viza berish va agentlik',
    pillar3Sub: 'Visa Issuance Agency / Viza agentligi',
    pillar3Desc: 'E-7, E-9, D-2, F-4 immigratsiya hujjatlarini rasmiylashtirish va uzaytirish',
    pillar4Title: 'Koreyada o‘qish va til kurslari',
    pillar4Sub: 'Study Abroad / Koreyada ta’lim',
    pillar4Desc: 'Universitetlarga qabul va qonuniy D-2 ishlash ruxsatnomasi',
    pillar5Title: 'Mehmonxona tozaligi mutaxassisi',
    pillar5Sub: 'Housekeeper / Xona tozalovchi',
    pillar5Desc: 'Jeju elita mehmonxonalari uchun xona tozalash mutaxassislari',
    companyName: 'Roksan Evergreen Co., Ltd.',
    address: '107-6, Seogwang-ro, Jeju-si, Jeju-do, Koreya',
    ceo: 'Rahbar : Chan-sik Kim',
    bizNum: 'Ro‘yxat raqami : 616-81-02802',
    phone: 'Telefon : +82-64-711-8578 / +82-10-5731-8578',
    email: 'Email : roksan22@daum.net',
    affiliates: 'Tegishli tashkilotlar'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('ko');

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
